### ISSUE TITLE
Hi. Help?

### ISSUE THREAD

**Issue by abdlmutii** [bislara/bislara#4]
How did you do the activity? Its dosen't work with me

**Comment by bislara** [comment]
Hi, checkout the below link
https://github.com/bislara/bislara/blob/master/.github/workflows/update-readme.yml

Also dont forget to create a github secret token in the settings

**Comment by abdlmutii** [comment]
> Hi, checkout the below link https://github.com/bislara/bislara/blob/master/.github/workflows/update-readme.yml
> 
> Also dont forget to create a github secret token in the settings

Hey bro. This what i do step by step. Can u tell me what i do wrong?

1 i put start & end activity section
```html
<!--START_SECTION:activity-->

<!--END_SECTION:activity-->
```

2 i make GitHub token from settings => developer settings => generate token

3 i make a repo secret with my token and called MY_SECRET_GITHUB_TOKEN

4 i make workflow file 
```yaml
name: Update README

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET_GITHUB_TOKEN }}
```
